Update

diff --git a/uit-client_2.0-1_amd64/usr/sbin/uit-screenshot b/uit-client_2.0-1_amd64/usr/sbin/uit-screenshot
--- a/uit-client_2.0-1_amd64/usr/sbin/uit-screenshot
+++ b/uit-client_2.0-1_amd64/usr/sbin/uit-screenshot
@@ -1,20 +1,36 @@
-#!/bin/bash
-systemSerial=$(dmidecode --string system-serial-number 2>/dev/null)
-if [[ -z $systemSerial ]]; then
-	systemSerial=$(cat /sys/class/dmi/id/product_serial)
-fi
-tagNum=$(uit-cli --serial "${systemSerial}" --key "client_lookup_by_serial" --value "${systemSerial}" --get | jq -r '.tagnumber' 2>/dev/null)
-while [[ -z $tagNum ]]; do
-	echo "Unable to find tag number for system serial ${systemSerial}"
-	sleep 5
-	tagNum=$(uit-cli --serial "${systemSerial}" --key "client_lookup_by_serial" --value "${systemSerial}" --get | jq -r '.tagnumber' 2>/dev/null)
-done
+#!/usr/bin/env bash
+
+function cleanup {
+	rm -f /tmp/screenshot
+	pkill -P $$
+}
+trap 'cleanup' EXIT
+
+function clientLookup() {
+	local systemSerial=$(dmidecode --string system-serial-number 2>/dev/null)
+	if [[ -z $systemSerial ]]; then
+		systemSerial=$(cat /sys/class/dmi/id/product_serial)
+	fi
+	local tagNum=$(uit-cli --serial "${systemSerial}" --key "client_lookup_by_serial" --value "${systemSerial}" --get | jq -r '.tagnumber' 2>/dev/null)
+	while [[ -z $tagNum ]]; do
+		echo "Unable to find tag number for system serial ${systemSerial}, retrying in 5 seconds..."
+		sleep 5
+		tagNum=$(uit-cli --serial "${systemSerial}" --key "client_lookup_by_serial" --value "${systemSerial}" --get | jq -r '.tagnumber' 2>/dev/null)
+	done
+	echo "${tagNum}"
+}
 
 while true; do
-	fbgrab - > /tmp/screenshot.png
-	printf '%s' "api_post|${tagNum}|live_image|/tmp/screenshot.png" | /opt/uit-toolbox/parse
-	# Check if cancel job has been sent
-	if [[ -n $(printf "%s" "api_get|job_name|tagnumber|${tagNum}" | /opt/uit-toolbox/parse) ]]; then
+	if [[ ! -f /root/screenshot.png ]]; then
+		mkfifo /tpm/screenshot
+	fi
+
+	tag=$(clientLookup)
+	fbgrab - > /tmp/screenshot
+	# printf '%s' "api_post|${tag}|live_image|/tmp/screenshot" | /opt/uit-toolbox/parse
+	uit-cli --tag "${tag}" --key "live_screenshot" --value "/tmp/screenshot" --post
+	# Update more frequently if a job is active
+	if [[ -n $(printf "%s" "api_get|job_name|tagnumber|${tag}" | /opt/uit-toolbox/parse) ]]; then
 		sleep 3
 	else
 		sleep 10
